version: "3.8"

services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=mysql://realtime_server:password@db/realtime_server
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - GUARDIAN_SECRET_KEY=${GUARDIAN_SECRET_KEY}
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=realtime_server
      - MYSQL_USER=realtime_server
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
